# Generated by Django 3.2.4 on 2021-06-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Name of the Author')),
                ('picture', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Pic of the Author')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=60, verbose_name='Category of the Article')),
                ('title', models.CharField(max_length=60, verbose_name='Title of the Article')),
                ('summary', models.TextField(default=None, null=True, verbose_name='summary of the Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.authors')),
            ],
        ),
    ]
